# Generated by Django 5.2.1 on 2025-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alumnos_curso',
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='Plataforma.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='max_alumnos',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
